### ISSUE TITLE
Suggest Project Root README Design

### ISSUE THREAD

**Issue by imbf** [JNU-econovation/webper#80]
### 현재 README에 대한 고찰

현재 작성해주신 README는 제가 보았을 때 크게 3부분으로 나뉘는 것 같습니다.

1. webper 프로젝트에 대한 소개
2. Project Convention
3. git을 사용해 webper를 개발하는데 필요한 정보들 및 특정 방법

README를 작성하는 목적을 **사용자가 우리 프로젝트를 참고 및 사용할 때 정보 제공**이라고 생각했을 때 1번과 2번이 들어가는건 아주 찬성이지만, 3번이 굳이 들어가야 할까??에 대해서는 같이 생각을 좀 해봐야 할 것 같아요!!

### 내가 생각하는 개선되었으면 하는 README 

1. 공통
   - webper 서비스 설명
   - 팀 소개
   - Convention (ex. Commit Message, Branch, ...)
   - 서비스 아키텍처 (통신하는 모듈들의 흐름을 한 눈에 볼 수 있도록 하는 다이어그램 정도면 적당)
     - 예시
       ![Pinpoint Architecture](https://pinpoint-apm.github.io/pinpoint/images/pinpoint-architecture.png)
   - 시연 영상
     - 최종 발표에 첨부된 영상 등을 짜집기 해서 만들면 좋을 것 같다.
   - 서비스 실행 방법 (선택)
     - 각 모듈을 개별적으로 띄우는 방법
     - 스크립트 파일을 통해 명령어 하나로써 모든 모듈을 띄우는 방법
       - 스크립트 파일을 작성해서 이 방법을 안내하면 최고긴 한데, 고려해야 할 부분이 많기도 하네요! 고민해 봅시다.
         - 각 모듈들은 어떠한 포트로 통신하게 할 것인가?
         - 각 모듈들에 연결된 데이터베이스와 같은 시스템들은 어떻게 안내해야 하는걸까?
     - 아예 명시 하지 않는 방법
     - 도커로 이미지 만들어서 제공하는 방법
     - ...

2. React (서영, 진영)
   - 이 부분은 담당하신 분들이 자유롭게 작성해도 좋을 것 같아요!!

3. Spring (종진)
   - 기술 스택 안내
   - 각종 다이어그램 (server 구조 및 프로세스 안내)
     - ERD
     - Sequence Diagram
     - Architecture Diagram
   - 운영 자동화 도구 안내

4. pupeeteer (서영, 진영)
   - 이 부분은 담당하신 분들이 자유롭게 작성해도 좋을 것 같아요!!

**Comment by imbf** [comment]
@vvvpiano @kanamycine 
제 관점에서 1시간정도 고민하면서 작성한거라 많이 부족할 것 같지만 ㅜㅜㅜ 너그럽게 양해 부탁드리구요
**(작성법을 어떻게 하든 우리의 목적은 좋은 품질의 README.md 파일 생성이니!!)**

의견 주시면 좋을것 같아요!!!

**Comment by vvvpiano** [comment]
readme 고찰 부분에서 1, 2, 3번 정리해주신 것에 대한 제 의견은
2, 3번은 굳이 필요 없을 것 같다! 라는 생각입니다ㅎㅎ  사실 종진님이 2번과 3번을 구분하신 경계점이 어떻게 되는지 잘 모르겠어서요! 2, 3번은 저희가 지속적으로 코드 리팩토링을 해나가는데 잊지 않고 참고해야 할 점이 있다면 github의 wiki로 내용을 옮기는 것도 괜찮을 것 같아요! 

개선안 부분에 대해서 의견을 정리해보겠습니다!
공통 내용에 대해서는 아주 동의하는 바입니다.  서비스 아키텍쳐 부분은 최종발표에 사용되었던 다이어그램 모습정도로 상상하면 될까요? 
그리고 서비스 실행 방법을 명시해 놓는 부분은 당장은 완성이 어려울 것 같지만 추후에 보충한다면 좋을 것 같다고 생각합니다! 종진님은 꾸준히 리팩토링을 해오셨지만 저는 그 뒤에 아직 만지지 못해서요(ㅋㅋㅋㅠ.. 지금 하고있는 프로젝트과제 마무리하면 최대한 빠르게 착수해보겠습니다..) 바뀐 포트번호를 아직 적용시키지 않았고 코드포맷팅 및 리팩토링을 조금 더 하고싶습니다! 다른 부분은 괜찮지만 일단 포트번호가 적용이 안된 상태라서 프론트라인이랑 통신이 아마 안될거에요!

시연 영상은 최종발표 ppt에 들어갔던 녹화영상이 클립단위로 원본이 저한테 있습니다! 필요하면 이거 사용해도 좋을 것 같고, 우리 최종발표영상 자체를 사용하는 방법도 있을 것 같은데, 이만큼 큰 용량의 파일을 올리는게 가능한지는 저두 잘 모르겠네요!(2020winter dev처럼 시연영상이 에코노 유튜브에 올라온다면 그 링크를 올리는 것은 아주 좋을 것 같습니다!)

react와 puppeteer부분은
react
- redux를 통한 상태관리 설명
- 대략적인 컴포넌트 설명
- react단에서 담당하는 기능 간단 설명

puppetter
- puppetter 서버의 기능
- puppetter 구조를 설명하는 다이어그램
정도로 대략 생각해 봤습니다~~

**Comment by imbf** [comment]
1. 사실 Project Convention 들어갔으면 하는 이유는 추후에 저희 팀 또는 다른 오픈소스 사용자들이 저희 코드에 기여할 때 "컨벤션은 이렇게 해라~~" or "커밋 메시지 히스토리 볼 때 참고해라" 라는 목적으로 있었으면 좋겠다는 생각이네요 ㅎㅎ!! **사실 없어도 크게 문제가 될 것 같지는 않아요!! (제가 넣고 싶은건 2번 3번 통틀어서 Commit Message Convention 정도?)**

2. 서비스 아키텍처는 되도록이면 최종발표 때 사용 했던걸 가져와서 사용하고 서비스 실행 방법 안내는 조금 미루도록 하죠!!

3. 서영님이 공통부분의 어디를 담당해주실 수 있을까요??

4. react + puppeteer 부분은 좋습니다!!

5. 저는 개인적으로 다음주 일요일(11월 15일)까지는 서비스 실행 방법 안내 목차 빼고 작성이 다 되었으면 싶은데 어떻게 생각하시나요 ㅎㅎ?

**Comment by vvvpiano** [comment]
2, 4, 5 저도 좋습니다~!!
1. 그런 목적이라면 리드미로 노출시키는게 더 맞겠네요! 커밋메세지 컨벤션을 리드미에 넣는것 동의합니다! 다만 프로젝트 설명이 우선이고 현실적으로 컨트리뷰트 하려는 사람은 많지 않을 것 같으니 전체적인 설명 아래에 들어가면 좋을 것 같아요!
3. 저는 webper서비스 설명, 팀소개, 시연영상정도 맡고싶습니다! 종진님은 어떠세요?

**Comment by imbf** [comment]
1. 네네 너무 좋은 것 같아요!!

2. 네네 좋습니다!! 제가 나머지 부분 확실히 진행하도록 하겠습니다!! 내일 까지 제가 맡은 공통부분 작성해서 PR 날리겠습니다~!
